
networks:
  inception:

volumes:
  mariadb-data:
    driver: local
    driver_opts:
      o : "bind"
      type : "none"
      device : "/home/idelfag/data/mariadb"
  wordpress-data:
    driver: local
    driver_opts:
      o : "bind"
      type : "none"
      device : "/home/idelfag/data/wordpress"

services:
  mariadb:
    build: requirements/mariadb/
    image: mariadb
    pull_policy: build
    container_name: mariadb
    networks:
      - inception
    env_file: ".env"
    volumes:
      - mariadb-data:/var/lib/mysql
    restart: always
  
  nginx:
    build: requirements/nginx/
    image: nginx
    pull_policy: build
    container_name: nginx
    networks:
      - inception
    volumes:
      - wordpress-data:/var/www/html
    ports:
      - 443:443
    depends_on:
      - wordpress
    restart: always
  
  wordpress:
    build : requirements/wordpress/
    image : wordpress
    container_name : wordpress
    pull_policy: build
    depends_on:
      - mariadb
    networks:
      - inception
    env_file:
      - .env
    volumes:
      - wordpress-data:/var/www/html
    restart: always
